dist: bionic
language: java
jdk:
  - openjdk11
script:
  - wget https://services.gradle.org/distributions/gradle-6.1.1-bin.zip
  - unzip gradle-6.1.1-bin.zip
  - export PATH=gradle-6.1.1/bin:$PATH
  - gradle -version
  - gradle clean build installDist
