---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-http-lb
spec:
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30989
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-grpc-lb
spec:
  selector:
    app: app-frontend
  ports:
    - protocol: TCP
      port: 5556
      nodePort: 30556
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  selector:
    matchLabels:
      app: app-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: app-frontend
          image: app-frontend:1.0.0-SNAPSHOT
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          ports:
            - name: grpc
              containerPort: 5556
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 500m
