---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
spec:
  selector:
    app: kafka-zookeeper
  ports:
    - protocol: TCP
      port: 9092
      nodePort: 30992
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-zookeeper
  template:
    metadata:
      labels:
        app: kafka-zookeeper
    spec:
      containers:
        - name: kafka-zookeeper
          image: kafka-zookeeper:2.11_2.3.0
          imagePullPolicy: Never
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: kafka
              containerPort: 9092
              protocol: TCP
            - name: zookeeper
              containerPort: 2181
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests:
              memory: 2Gi
              cpu: 500m
