server:
  port: 8081
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: backend-service-id
        serviceName: backend-${spring.application.name}
        tags: appType=backend, appVersion=1.0.0
        healthCheckPath: /services/health
        healthCheckInterval: 15s
      config:
        enabled: true
  application:
    ID: myConsulBackendApp
    name: myConsulBackendApp
management:
  ID: myConsulBackendApp-management
  Name: myConsulBackendApp-management
  server:
    port: 4452