spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: custom-service-id
        serviceName: myprefix-${spring.application.name}
        tags: appType=frontend, appVersion=1.0.0
  application:
    ID: myConsulApp
    name: myConsulApp
management:
  ID: myConsulApp-management
  Name: myConsulApp-management
  server:
    port: 4452